fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/carstencodes/flake518
    # A wrapper around flake8 that support pyproject.toml
    rev: v1.6.0
    hooks:
    -   id: flake518
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.331
    hooks:
    -   id: pyright
-   repo: local
    hooks:
    # Run unit unit tests inside a Docker container.
    # It might take some time initially to download and build the image,
    # but it will be faster on subsequent runs.
    -   id: pytest
        name: pytest
        # entry: python3 tests/docker/run_dockerized_tests.py
        entry: poetry run pytest
        language: system
        always_run: false
        pass_filenames: false
