ARG INPUT_IMAGE_NAME

FROM ${INPUT_IMAGE_NAME} as exp_base


# Configure and install Poetry
# Based on https://stackoverflow.com/questions/72465421/how-to-use-poetry-with-docker
ENV POETRY_VERSION=1.3.2
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache

# Install poetry separated from system interpreter
RUN python -m venv $POETRY_VENV \
    && $POETRY_VENV/bin/pip install -U pip setuptools \
    && $POETRY_VENV/bin/pip install poetry==${POETRY_VERSION}

# Add `poetry` to PATH
ENV PATH="${PATH}:${POETRY_VENV}/bin"

ARG EXP_DIR
# Create the directory for the code
RUN mkdir -p $EXP_DIR
WORKDIR $EXP_DIR
